Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

namespace codylab.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Controllers/PagesController.cs
using Microsoft.AspNet.Mvc;

namespace codylab.Controllers
{
    public class PagesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Views/Shared/Partials/HomeNav.cshtml
<header class="trans">
    <div class="hwrap">
        <a asp-controller="Pages" asp-action="Index" class="header-logo">
            <img src="/images/logo.png" alt="">
        </a>

        <nav>
            <a href="" ng-click="vm.gotoWorks()">{{ trans('nav.works') }}</a>
            <a href="{{ URL::route('services') }}">{{ trans('nav.services') }}</a>
            <a href="{{ URL::route('about') }}">{{ trans('nav.about') }}</a>
            <a href="{{ URL::route('contact') }}">{{ trans('nav.contact') }}</a>
        </nav>
    </div>

    <div id="burger">
        <div class="x"></div>
        <div class="y" style="display: block;"></div>
        <div class="z"></div>
    </div>
</header>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"]</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/css/app.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="~/css/app.min.css" asp-append-version="true" />
        </environment>       
    </head>
    <body id="home">
        @RenderBody()

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
        </environment>
        
        <environment names="Staging,Production">
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>